# Page settings

baseURL = "http://example.org/"
languageCode = "en"
title = ""
theme = "resume"
googleAnalytics = "UA-XXXXXXX-Y"




[params]
    author = "CowboySmall"
    description = "DevResume - Bootstrap 4 Resume/CV Template For Software Developers"


    primaryColor = "#54B689"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "Soufiane OUDDAF"
        tagline = "Full Stack Developer"
        avatar = "avatar.png"





    [params.contact]
        enable = true
        location = "Tétouan, Morocco"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:#"
        text = "+212 6 06 75 23 13"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "soufiane.odf@gmail.com"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "https://soufianeodf.github.io/"
        text = "www.soufianeodf.github.io"





    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "HTML5/CSS3/Bootstrap"
        [[params.skills.list.items]]
        details = "JavaScript/jQuery/Ajax/Json"
        [[params.skills.list.items]]
        details = "WordPress/Hugo"
        [[params.skills.list.items]]
        details = "React/React-Native/Redux"
        [[params.skills.list.items]]
        details = "Java EE/Hibernate/Spring MVC/JSF"
        [[params.skills.list.items]]
        details = "MySQL/Firebase"
        [[params.skills.list.items]]
        details = "Git/GitHub/GitFlow"


        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Effective communication"
        [[params.skills.list.items]]
        details = "Team player"
        [[params.skills.list.items]]
        details = "Strong problem solver"
        [[params.skills.list.items]]
        details = "Good time management"





    [params.education]
        enable = false

        [[params.education.list]]
        degree = "MSc in Computer Science"
        university = "University College London"
        dates = "2010 - 2011"
        [[params.education.list]]
        degree = "BSc Maths and Physics"
        university = "Imperial College London"
        dates = "2007 - 2010"





    [params.awards]
        enable = true

        [[params.awards.list]]
        name = "DELF B2"
        body = "French studies diploma"
        date = "2015"





    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "Arabic"
        level = "Native"
        [[params.languages.list]]
        name = "English"
        level = "Professional"
        [[params.languages.list]]
        name = "Spanish"
        level = "Professional"
        [[params.languages.list]]
        name = "French"
        level = "Professional"




    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Reading/writing blogs"
        [[params.interests.list]]
        name = "Footing"




    [params.summary]
        enable = true
        text = "Hello there! My name is Soufiane OUDDAF, and I'm a Full Stack Web and Mobile App Developer. I started my journey as a computer science student, and there I discovered my passion toward the programming and web development in general. Ever since I have fallen in love with programming and spend most of my days taking my craft to the next level. "



    [params.myExperience]
        enable = true

        [[params.myExperience.list]]
        title = "TRAINING"
        dates = "2019 - 2020"
        company = "Everis"
        details = "One month Training in JAVA EE / ANGULAR within EVERIS."



    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "ABDELMALEK ESSAADI UNIVERSITY"
        dates = "2019 - 2021"
        company = ""
        details = "Master's degree in Computer Science and Engineering."

        [[params.experience.list]]
        title = "SPECIALIZED TECHNICIAN"
        dates = "2019 - 2020"
        company = ""
        details = "Institute Specialized In Offshoring (ISMO)"

        [[params.experience.list]]
        title = "ABDELMALEK ESSAADI UNIVERSITY"
        dates = "2015 - 2019"
        company = ""
        details = "Bachelor's degree in Computer Science."

        [[params.experience.list]]
        title = "IMAM EL GHAZALI HIGH SCHOOL"
        dates = "2014 - 2015"
        company = ""
        details = "Scientific baccalaureat in maths sciences B"





    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "REAL ESTATE WEBSITE"
        meta = ""
        tagline = "A real estate website."

        [[params.projects.list]]
        title = "E-COMMERCE WEBSITE"
        meta = ""
        tagline = "A simple e-commerce website."

        [[params.projects.list]]
        title = "NBA App"
        meta = "Open Source"
        tagline = "A simple NBA mobile app."






    [params.information]
        enable = false

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2018 · Lorem Ipsum"
        [[params.information.list.items]]
        details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "Climbing, Snowboarding, Photography, Travelling"






    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/soufianeodf"
        title = "soufianeodf"
        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "//twitter.com/OdfSoufiane"
        title = "@OdfSoufiane"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/soufiane-ouddaf-396348178/"
        title = "soufiane-ouddaf-396348178"





